### ISSUE TITLE
下载RTSP视频不能自动停止的问题

### ISSUE THREAD

**Issue by zqh000** [NueXini/RTSP-Patrina#1]
作者您好！
目前使用软件下载IPTV的回放，目前遇到这样的问题，到了节目停止的时间不能自动停止，需要手动点击停止才会停止录制，而此时已经没有视频或音频了。举个例子，IPTV的回放地址是如下格式：
rtsp://183.252.166.199/PLTV/88888888/224/3221225998/10000100000000060000000002296745_0.smil?playseek=年月日时分秒-年月日时分秒，比如要回放录制2022年2月24日12点00分00秒-2022年2月24日12点30分00秒的视频，就是rtsp://183.252.166.199/PLTV/88888888/224/3221225998/10000100000000060000000002296745_0.smil?playseek=20220224120000-20220224123000
按理来说半个小时即可停止，但是过了半小时后仍然显示在录制中，尽管文件大小已经不再增加。
请帮忙协助修复这一问题，谢谢！

**Comment by NueXini** [comment]
如果文件大小不再增长,说明录制已经完成,可直接退出软件,并不会影响录制文件
或者尝试下面方法
TCP录制的话,请在 MP2T over TCP.cfg 文件中,添加一行
```bash
#DEFINE [Stop] x-notice: 2101
```
像这样
![1](https://user-images.githubusercontent.com/34617094/155477244-26a113ef-ad6f-407f-849d-19575a03e851.png)
该方法我广东地区测试有效,UDP录制暂时没办法

**Comment by zqh000** [comment]
谢谢作者，主要是批量下载时，第一个不自动停止，第二个也不会继续录制，我试下您说的办法，谢谢！&nbsp;


张秋航
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NueXini/RTSP-Patrina] 下载RTSP视频不能自动停止的问题 (Issue #1)





 
如果文件大小不再增长,说明录制已经完成,可直接退出软件,并不会影响录制文件
 或者尝试下面方法
 TCP录制的话,请在 MP2T over TCP.cfg 文件中,添加一行
 #DEFINE [Stop] x-notice: 2101
 
像这样
 
 该方法我广东地区测试有效,UDP录制暂时没办法
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqh000** [comment]
[](url
![QQ图片20220224152937](https://user-images.githubusercontent.com/40236886/155478270-74e43b31-b92b-488d-b3ba-fc8a487287d0.png)
)
另外有个建议吧，能否把这个下载器zuo做一个版本，类似于图片这样的，这样比较方便选台和更改回录的时间。

**Comment by NueXini** [comment]
软件开源的,可以自己去修改
